# Generated by Django 3.1.3 on 2020-11-12 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_start_date', models.DateTimeField(auto_now_add=True)),
                ('lot_title', models.CharField(blank=True, default='', max_length=100)),
                ('lot_description', models.TextField(help_text='Enter a brief description of the your lot', max_length=1000)),
                ('lot_start_price', models.CharField(default=100, max_length=100)),
                ('lot_end_date', models.DateField()),
                ('lot_last_bet_price', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, choices=[('b', 'being traded'), ('c', 'completed')], default='b', help_text='Lot is available for purchase', max_length=1)),
                ('lot_author', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL)),
                ('lot_last_bet_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_last_bet_user', to=settings.AUTH_USER_MODEL, verbose_name='Who placed the bet')),
            ],
            options={
                'db_table': 'auction',
                'ordering': ['lot_end_date'],
            },
        ),
    ]
