# Generated by Django 3.1.3 on 2020-11-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0003_auto_20201112_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='lot_last_bet_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
